/**
 * Helper script to create .env file from user input or existing config
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(prompt) {
    return new Promise((resolve) => {
        rl.question(prompt, resolve);
    });
}

async function createEnvFile() {
    console.log('📝 Creating .env file...\n');
    
    // Check if .env already exists
    const envPath = path.join(__dirname, '..', '.env');
    if (fs.existsSync(envPath)) {
        const overwrite = await question('.env file already exists. Overwrite? (y/n): ');
        if (overwrite.toLowerCase() !== 'y') {
            console.log('Cancelled.');
            rl.close();
            return;
        }
    }
    
    // Check if supabase-config.js exists and try to extract values
    const configPath = path.join(__dirname, '..', 'supabase-config.js');
    let existingUrl = '';
    let existingKey = '';
    
    if (fs.existsSync(configPath)) {
        const configContent = fs.readFileSync(configPath, 'utf8');
        const urlMatch = configContent.match(/SUPABASE_URL\s*=\s*['"]([^'"]+)['"]/);
        const keyMatch = configContent.match(/SUPABASE_ANON_KEY\s*=\s*['"]([^'"]+)['"]/);
        if (urlMatch) existingUrl = urlMatch[1];
        if (keyMatch) existingKey = keyMatch[1];
    }
    
    const url = await question(`Supabase URL${existingUrl ? ` [${existingUrl}]` : ''}: `) || existingUrl;
    const anonKey = await question(`Supabase Anon Key${existingKey ? ' [***]' : ''}: `) || existingKey;
    const serviceKey = await question('Supabase Service Role Key (optional, for migrations): ');
    
    const envContent = `# Supabase Configuration
# Generated by create-env.js

SUPABASE_URL=${url}
SUPABASE_ANON_KEY=${anonKey}
${serviceKey ? `SUPABASE_SERVICE_KEY=${serviceKey}` : '# SUPABASE_SERVICE_KEY=your-service-role-key-here'}
`;

    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ .env file created successfully!');
    console.log('💡 You can now run: npm run setup\n');
    
    rl.close();
}

createEnvFile().catch(console.error);

